spring:
  application:
    name: demande
  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    # Enable logging for SQL statements
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    # Enable logging for SQL parameter values

spring.jpa.properties.hibernate.format_sql: true
spring.jpa.show-sql: true
# Enable Hibernate SQL formatting


