spring:
  application:
    name: demande
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/PFE-network
          jwk-set-uri: http://localhost:9090/realms/PFE-network/protocol/openid-connect/certs   

