spring:
   application:
      name: demande
   config:
      import: optional:configserver:http://config-server:8888
   security:
      oauth2:
         resourceserver:
           jwt:
               issuer-uri: http://keycloak:8080/realms/GestionDemande
               jwk-set-uri: http://keycloak:8080/realms/GestionDemande/protocol/openid-connect/certs