spring:
   application:
      name: auth
   config:
      import: optional:configserver:http://localhost:8888
   security:
      oauth2:
         client:
            registration:
               keycloak:
                  client-id: rne-rest-api
                  authorization-grant-type: authorization_code
                  scope: openid