eureka:
  instance:
    hostname: config-server
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka

server:
   port: 8082

spring:
   application:
      name: demande
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://db:5432/RNEdb?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true&currentSchema=demande
      username: postgres
      password: youssef31

   jpa:
      hibernate:
         ddl-auto: update
         dialect: org.hibernate.dialect.PostgreSQLDialect  
      properties:
         hibernate:
            format_sql: true
      show-sql: true  

management:
   tracing:
      sampling:
         probability: 1.0

logging:
   level:
      org.springframework.security: DEBUG
      org.hibernate: DEBUG  # To log Hibernate activities
