eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: referentiel
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/referentiel/**
           
management:
  tracing:
    sampling:
      probability: 1.0
