eureka:
   instance:
      hostname: localhost
   client:
      service-url:
         defaultZone: http://localhost:8761/eureka


server:
   port: 8081
spring:
   application:
      name: referentiel
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://postgresql-zaineb.alwaysdata.net:5432/zaineb_rnebd?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true&currentSchema=referentiel
      username: zaineb
      password: Zaineb.123


   jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: referentiel
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
   tracing:
      sampling:
         probability: 1.0