eureka:
   instance:
      hostname: localhost
   client:
      service-url:
         defaultZone: http://localhost:8761/eureka


server:
   port: 8081
spring:
   application:
      name: referentiel
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/RNEdb?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true&currentSchema=referentiel
      username: postgres
      password: youssef31
      #url: jdbc:postgresql://postgresql-youssef31.alwaysdata.net:5432/youssef31_rnedb?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true&currentSchema=referentiel
      #username: youssef31
      #password: Youssef*31
    

   jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: referentiel
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
   tracing:
      sampling:
         probability: 1.0