eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8083

spring:
  application:
    name: request
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/rneBD?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true&currentSchema=demande
    username: postgres
    password: Zaineb123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: demande
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  tracing:
    sampling:
      probability: 1.0