version: '3.8'
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8182:8080"  # Mapping du port 8182 de l'hôte vers le port 8080 du conteneur Keycloak
    command:
      - "start-dev"
